version: '2'
services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    expose:
    - "53/tcp"
    - "53/udp"
    cap_add:
      - NET_ADMIN
    command: ['--log-facility=-', '--log-queries']

  flyby:
    build: .
    environment:
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      FLYBY_DYNAMO_HOST: 'http://localdynamodb:7777'
    links: [localdynamodb, dnsmasq]
    ports: ["80:80", "5000:5000"]
    command: ['flyby', 'start']
    depends_on:
    - localdynamodb
    - dnsmasq

  localdynamodb:
    build:
      context: .
      dockerfile: LOCALDYNAMODB.dockerfile
    ports: ["7777:7777"]

  foo:
    image: tutum/hello-world
    ports: ["9000:80"]

  bar:
    image: tutum/hello-world
    ports: ["9001:80"]
