version: '2'
services:
  flyby:
    build: .
    environment:
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
    ports: ["80:80", "5000:5000"]
    command: ['flyby', 'start', '--dynamo-host', 'http://moto:8000']
  moto:
    build:
      context: .
      dockerfile: LOCALDYNAMODB.dockerfile
    expose: ["7777"]