version: '2'
services:
  flyby:
    build: .
    environment:
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      FLYBY_ENVIRONMENT: production
    ports: ["80:80", "5000:5000"]
    command: ['flyby', 'start', '--dynamo-host', 'http://localdynamodb:7777']
    depends_on:
    - localdynamodb
  localdynamodb:
    build:
      context: .
      dockerfile: LOCALDYNAMODB.dockerfile
    ports: ["7777:7777"]
  foo:
    image: tutum/hello-world
    ports: ["9000:80"]

